"""Initial migration

Revision ID: 1c3b1aa5f5b7
Revises: 
Create Date: 2026-01-03 21:28:59.395676+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c3b1aa5f5b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'LOCKED', name='accountstatus'), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('key_provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('api_passphrase', sa.Text(), nullable=True),
    sa.Column('usdc_balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('matic_balance', sa.Numeric(precision=20, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_accounts_address', 'accounts', ['address'], unique=False)
    op.create_index('ix_accounts_status', 'accounts', ['status'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('condition_id', sa.String(length=66), nullable=False),
    sa.Column('question_id', sa.String(length=66), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('yes_token_id', sa.String(length=100), nullable=False),
    sa.Column('no_token_id', sa.String(length=100), nullable=False),
    sa.Column('yes_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('no_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('spread', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'RESOLUTION_PENDING', 'RESOLVED', name='marketstatus'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_id')
    )
    op.create_index('ix_markets_category', 'markets', ['category'], unique=False)
    op.create_index('ix_markets_end_date', 'markets', ['end_date'], unique=False)
    op.create_index('ix_markets_status', 'markets', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PAUSED', 'ERROR', 'STOPPED', name='agentstatus'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.Enum('ORACLE_LATENCY', 'BINARY_ARBITRAGE', 'LIQUIDITY_PROVISION', 'CUSTOM', name='strategytype'), nullable=False),
    sa.Column('strategy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_position_size', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_index('ix_agents_strategy', 'agents', ['strategy_type'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'market_id', 'side', name='uq_position')
    )
    op.create_index('ix_positions_is_closed', 'positions', ['is_closed'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.Enum('ORACLE_LATENCY', 'BINARY_ARBITRAGE', 'LIQUIDITY_PROVISION', 'CUSTOM', name='strategytype'), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_outcome', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('expected_payout', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('verification_source', sa.String(length=100), nullable=True),
    sa.Column('verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'VERIFIED', 'EXECUTED', 'EXPIRED', 'REJECTED', name='signalstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_detected_at', 'signals', ['detected_at'], unique=False)
    op.create_index('ix_signals_status', 'signals', ['status'], unique=False)
    op.create_index('ix_signals_strategy', 'signals', ['strategy_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_value', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('clob_order_id', sa.String(length=100), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('filled_size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clob_order_id')
    )
    op.create_index('ix_orders_clob_id', 'orders', ['clob_order_id'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('clob_trade_id', sa.String(length=100), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_logs_account', 'trade_logs', ['account_id'], unique=False)
    op.create_index('ix_trade_logs_executed_at', 'trade_logs', ['executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_logs_executed_at', table_name='trade_logs')
    op.drop_index('ix_trade_logs_account', table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_clob_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('tasks')
    op.drop_index('ix_signals_strategy', table_name='signals')
    op.drop_index('ix_signals_status', table_name='signals')
    op.drop_index('ix_signals_detected_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_positions_is_closed', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_agents_strategy', table_name='agents')
    op.drop_index('ix_agents_status', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_markets_status', table_name='markets')
    op.drop_index('ix_markets_end_date', table_name='markets')
    op.drop_index('ix_markets_category', table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_accounts_status', table_name='accounts')
    op.drop_index('ix_accounts_address', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
